package com.jll.cibus.role;

public enum Permits {

    //CRUD USERS
    USER_READ,
    USER_CREATE,
    USER_UPDATE,
    USER_DELETE,

    //CRUD PRODUCTS
    PRODUCT_READ,
    PRODUCT_CREATE,
    PRODUCT_UPDATE,
    PRODUCT_DELETE,

    //CRUD CATEGORY
    CATEGORY_READ,
    CATEGORY_CREATE,
    CATEGORY_UPDATE,
    CATEGORY_DELETE,

    //CRUD BRANCH
    BRANCH_READ,
    BRANCH_CREATE,
    BRANCH_UPDATE,
    BRANCH_DELETE,

    //CRUD TABLE AND STATUS CHANGE
    TABLE_READ,
    TABLE_CREATE,
    TABLE_UPDATE,
    TABLE_DELETE,
    TABLE_OPEN,
    TABLE_CLOSE,

    //CRUD ORDER AND STATUS CHANGE
    ORDER_READ,
    ORDER_CREATE,
    ORDER_UPDATE,
    ORDER_CANCEL,
    ORDER_CLOSE,
    ORDER_CHANGE_STATUS,

    //CRUD PAYMENT
    PAYMENT_CREATE,
    PAYMENT_READ,
    PAYMENT_UPDATE,
    PAYMENT_DELETE,

    //CRUD ORDER STATUS
    ORDER_STATUS_READ,
    ORDER_STATUS_CREATE,
    ORDER_STATUS_UPDATE,
    ORDER_STATUS_DELETE
}
